apiVersion: v1
kind: Namespace
metadata:
  name: fbjfghftgfghfghhf-staging
  labels:
    environment-id: env_e19863c3-7abf-4683-b869-a9e8b6ffbbdc
    project-id: project_f5c9bb11-f827-49bf-a7c1-8daf74a0dc4e
    project-name: fbjfghftgfghfghhf
    environment-name: staging
    organization-id: org_c50d7b26-1f2a-4a6e-b11e-469a86e002c8
